# Generated by Django 2.0.5 on 2018-07-01 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexInfo',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('menu', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='down_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='up_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='indexinfo',
            name='articles',
            field=models.ForeignKey(on_delete=True, to='Blog.Article'),
        ),
        migrations.AddField(
            model_name='indexinfo',
            name='category',
            field=models.ForeignKey(on_delete=True, to='Blog.Category'),
        ),
        migrations.AddField(
            model_name='indexinfo',
            name='comment',
            field=models.ForeignKey(on_delete=True, to='Blog.Comment'),
        ),
        migrations.AddField(
            model_name='indexinfo',
            name='tag',
            field=models.ForeignKey(on_delete=True, to='Blog.Tag'),
        ),
    ]
