# Generated by Django 2.0.5 on 2018-07-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20180701_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexinfo',
            name='articles',
        ),
        migrations.RemoveField(
            model_name='indexinfo',
            name='category',
        ),
        migrations.RemoveField(
            model_name='indexinfo',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='indexinfo',
            name='tag',
        ),
        migrations.DeleteModel(
            name='IndexInfo',
        ),
    ]
